const MSG = {
  'NO_APP_NAME':    'アプリケーション名を入力して下さい。',
  'SEN_PER_1_MORE': 'センサ値取得周期には1以上の値を指定して下さい。',
  'TEMP_INT':       '温度には数値を指定して下さい。',
  'HUMI_0_MORE':    '湿度には0以上の値を指定して下さい。',
  'ILLU_0_MORE':    '照度には0以上の値を指定して下さい。',
  'NO_TRIGGER':     'トリガ条件を指定して下さい。',
  'SND_PER_1_MORE': 'データ送信周期には1以上の値を指定して下さい。',
  'NO_SEND_DATA':   '送信するデータを選択して下さい。',
  'TRI_PER_0_MORE': '状態継続中の実行周期には0以上の値を指定して下さい。',
  'NO_IFT_EVT':     'IFTTT Eventを入力して下さい。',
  'NO_IFT_KEY':     'IFTTT Keyを入力して下さい。',
  'NO_BLK_ENT':     'BLOCKS エントリーポイントを入力して下さい。',
  'NO_BLK_PID':     'BLOCKS プロジェクトIDを入力して下さい。',
  'NO_BLK_KEY':     'BLOCKS APIトークンを入力して下さい。',
  'NO_BLK_MTY':     'BLOCKS メッセージタイプを入力して下さい。',
  'NO_SCRIPT':      'やりたいことを入力して下さい。',
  'CONF_APPL':      '確認',
  'APP_NAME':       'アプリケーション名',
  'TARG_BOARD':     'ターゲットボード',
  'OPT_BOARD':      'オプションボード',
  'APP_TYPE':       'アプリケーションタイプ',
  'CONF_GENERATE':  '以下の内容でアプリケーションを作成します。',
  'LIBRARIES':      'ライブラリ',
  'BLANK':''
};
