const MSG = {
  'NO_APP_NAME':    'Please enter an application name.',
  'SEN_PER_1_MORE': 'The sensing period enter greater than or equal to one.',
  'TEMP_INT':       'Please enter a numeric value to the temperature.',
  'HUMI_0_MORE':    'The humidity should be input greater than or equal to zero.',
  'ILLU_0_MORE':    'The illumination enter greater than or equal to zero.',
  'NO_TRIGGER':     'Please set trigger conditions.',
  'SND_PER_1_MORE': 'The send pediod enter grater then than or equal to one.',
  'NO_SEND_DATA':   'Please select values that send to the server.',
  'TRI_PER_0_MORE': 'Please enter a number greater than 0 to the interval.',
  'NO_IFT_EVT':     'Please enter an IFTTT event.',
  'NO_IFT_KEY':     'Please enter an IFTTT key.',
  'NO_BLK_ENT':     'Please enter a BLOCKS entry point.',
  'NO_BLK_PID':     'Please enter a BLOCKS project ID.',
  'NO_BLK_KEY':     'Please enter a BLOCKS API token.',
  'NO_BLK_MDY':     'Please enter a BLOCKS message type.',
  'NO_SCRIPT':      'Type what you want to do.',
  'CONF_APPL':      'Confirm',
  'APP_NAME':       'Application name',
  'TARG_BOARD':     'Target board',
  'OPT_BOARD':      'Option board',
  'APP_TYPE':       'Application type',
  'CONF_GENERATE':  'Create the application with the following contents.',
  'LIBRARIES':      'Libraries',
  'BLANK':''
};
